name: Fast checks

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter-c:
    name: Linter on C code
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v7

      - name: Lint check
        run:
          clang-format --dry-run --Werror $(find src tests -type f \( -name '*.c' -o -name '*.h' \))

  lint:
    name: Call Ledger Python linters
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_type_check: true
      src_directory: speculos
      setup_directory: .

  misspell:
    name: Check misspellings
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_spell_check.yml@v1
    with:
      ignore_words_file: .codespell-ignore
      skip_path: '*swagger-ui*,*/fonts/*'
