name: Fast checks

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:
# Cancel previous runs on this reference
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linter-c:
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_lint.yml@v1
    with:
      source: src tests
      repo_is_tool: true

  lint:
    name: Call Ledger Python linters
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_python_checks.yml@v1
    with:
      run_type_check: true
      src_directory: speculos
      setup_directory: .

  misspell:
    name: Check misspellings
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_spell_check.yml@v1
    with:
      ignore_words_file: .codespell-ignore
      skip_path: '*swagger-ui*,*/fonts/*'
